### PR TITLE
👌 IMPROVE: Upgrade GHA third-party actions

### PR DESCRIPTION
**Pull request by michaelborn**
Upgrades a few third-party action dependencies to avoid warnings and deprecations.

### CODE REVIEW

**Comment by jclausen** [comment]
The tests are all failing on this one.  Can you see if you can get them working?

**Comment by michaelborn** [comment]
> The tests are all failing on this one. Can you see if you can get them working?

Of course I can. :smile:

**Comment by michaelborn** [comment]
Merged in latest `master` and `development`, better luck now. :crossed_fingers:

**Comment by michaelborn** [comment]
Ugh. I have no idea why these test failures...

**Comment by jclausen** [comment]
Ah!  I know why.  You are doing this PR from your personal fork, which doesn't make the secrets used in the test available. I'll merge this in to `development`

**Pull request merged**
